# Generated by Django 3.2.9 on 2023-01-18 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uog', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uog.profile'),
        ),
    ]
