# Generated by Django 3.2.9 on 2023-01-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uog', '0010_auto_20230119_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='idcard',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
