# Generated by Django 3.2.9 on 2023-02-05 03:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uog', '0012_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdfs')),
                ('title', models.CharField(max_length=500)),
                ('department', models.CharField(blank=True, choices=[('Electrical and Computer Engineering', 'Electrical and Computer Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Hydrolics Engineering', 'Hydrolics Engineering'), ('COTM', 'COTM')], max_length=100, null=True)),
                ('batch', models.CharField(blank=True, choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year'), ('Fifth Year', 'Fifth Year')], max_length=100, null=True)),
                ('contributer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uog.profile')),
            ],
        ),
    ]
